### PR TITLE
Add GitHub test action

### LINKED ISSUE #85: Add CI?
Though there are tests, there's no CI to run them. If github actions works for you guys, I"m willing to contribute!

### PR DESCRIPTION
**Pull request by gaffneyc**
This adds a basic GitHub Action for running tests against all of the currently supported versions of CRuby. Tests are run on pushes to `main` and any pull request to `main`. It includes #86 since the committed Gemfile.lock doesn't work with Ruby 3.0.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Closes #85
Closes #86

### CODE REVIEW

**Comment by gaffneyc** [comment]
You can see an example of the tests running on my fork: https://github.com/gaffneyc/twirp-ruby/actions

**Comment by arthurnn** [comment]
LGTM

**Comment by wmatveyenko** [comment]
@gaffneyc can you add this - "By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license." to you PR?

Thanks!

**Comment by gaffneyc** [comment]
Not a problem, I've added it to the PR message

**Comment by wmatveyenko** [comment]
Thanks for your contribution.

**Pull request merged**
