### PR TITLE
Adds optional ActiveSupport notifications

### PR DESCRIPTION
**Pull request by woto**
Hi folks, I thought it would be cool to publish notifications through ActiveSupport::Notifications to be able to join twirp-rails with modern logging and monitoring gems like https://github.com/roidrage/lograge or https://github.com/rocketjob/rails_semantic_logger, cheers!

### CODE REVIEW

**Comment by marioizquierdo** [comment]
Looks like a good idea. However, since the ActiveSupport notifications always happen when hooks are called, maybe this can be implemented as a set of hooks? That way we can keep Twirp core clean of dependencies, and the hook system is used as intended.

**Comment by marioizquierdo** [comment]
I'm not familiarized with how `ActiveSupport:Notifications`, but here it is a suggestion to wrap your Twirp service with hooks:

```ruby
def active_support_notification_hooks(svc)
  svc.before do |rack_env, env|
    env[:active_support_notification_start] = Time.now
  end

  svc.on_success do |env|
    start = env[:active_support_notification_start]
    active_support_notification_publish('request.twirp', start)
  end

  svc.on_error do |twerr, env|
    start = env[:active_support_notification_start]
    active_support_notification_publish('request.twirp', start, twirp_error: twerr)
  end
end

def active_support_notification_publish(name, env, payload = {})
  start = env[:active_support_notification_start]
  finish = Time.now
  unique_id = uuid
  payload = {}
  ActiveSupport::Notifications.publish name, start, finish, unique_id, payload
end
```

Then you can wrap your service like this:
```ruby
svc = Example::HelloWorldService.new(handler)
active_support_notification_hooks(svc)
```

Another option would be to [make Rack Middleware](https://github.com/twitchtv/twirp-ruby/wiki/Service-Hooks#before-routed-rack-middleware) wrapping the Twirp service (`@app.call(rack_env)`) with notifications.

This may not be exactly what you want. I can see, the suggested code in this PR would send a notification for each hook invocation, even for other hooks. But let me know if this would help. We should try to avoid adding dependencies in Twirp, and instead provide methods for dependency injection when neccessary.

**Comment by woto** [comment]
Hi, thank you for your fast reply. Yes, you are right. Sending a notification for each hook was not a strict requirement, and we could easily refuse it. Also, I understand the point in your consideration of the clean core. But however `ActiveSupport::Notifications.publish` doesn't offer the same functionality on application performance monitoring as `ActiveSupport::Notifications.instrument` which uses `ActiveSupport::Notifications::Event` (eg #allocations, #cpu_time, #idle_time). Also i saw that modern gems don't hesitate to use them. For example Grape https://github.com/ruby-grape/grape/blob/9e6e0ec2b29a6ed89d0b37602652e9c159472623/lib/grape/endpoint.rb#L56 Anyway it's your library If I didn't convince you in the benefits, I will use the fork 😊

**Comment by marioizquierdo** [comment]
Thanks for understanding, and the clarification on the `instrument` method. I'm not opposed to use `ActiveSupport::Notifications`, but it will require some more discussion and validation before being integrated in the master branch. Because once a feature is in, then it is almost impossible to change or revert, just want to make sure it solves the right problem for the majority of users.

Maybe, the issue is having `before` and `on_success` hooks as different methods. Maybe it would be useful to define a wrapper hook, so it is easier to instrument notifications. What about something like this? Would it make sense for your use case?

```ruby
svc = Example::HelloWorldService.new(handler)

svc.wrap_call_rpc do |svc, env|
  ActiveSupport::Notifications.instrument('call.twirp', env) do
      scv.call_rpc(env)
  end
end
```

**Comment by Ziaw** [comment]
Hi, 

Wrapper hook may solve the instrument task. I have tree questions.

1. Why do we use ```call_rpc```, not `call()`?
2. Do you want to implement hook yourself or to @woto changes this PR?
3. Could it be better to use rails around hook pattern with yield?

```ruby
svc.around_call do |svc, env|
  ActiveSupport::Notifications.instrument('call.twirp', env) do
      yield
  end
end
```

**Comment by marioizquierdo** [comment]
Good questions.

I don't think `yield` here works as you may expect; it will try to yield to the current method, which probably is not receiving a block and will return `no block given (yield) (LocalJumpError)`. The Rails around hooks are methods, but here they are blocks.

I was calling the inner method `call_rpc` instead of just `call` because I though of passing the service, which is already a Rack app and already has a call method (with rack env, not twirp env). But if using `call` is easier to read, we can define an internal wrapper. Maybe this would read better?

```ruby
svc.around_call do |wrapped_svc, env|
  # here, env has keys from before hooks
  wrapped_svc.call(env) # calls rpc method, and all on_success or on_error hooks
  # here, env has :twirp_error if the rpc call returned an error
  # and any key that was set by on_success or on_error hooks
end
```

If we want to move forward with the around hook idea (I like it!), then we better move to a new PR. We could reference this PR from that one as a use case. I could implement it, but it will take me a week or two before I can focus on this. If you want to give it a try that would be great. I just ask to add proper tests, making sure it is generic and simple, covering all use-cases (e.g. what if an exception is raised within the hook? does it play well with other before/on_success/on_error hooks?).

**Comment by woto** [comment]
Hi, oops, It seems we didn't know all the features of ActiveSupport::Notifications. Seems we managed to do it with hooks ). I'll write back here later.

https://github.com/woto/twirp-ruby/blob/0db27d0bea1ef542a796782362dfa952ecfac60a/example/hello_world_server.rb
https://gist.github.com/woto/4bc9e0bf3d5ef0cabaebd581cac17b12 (with :exception key)
https://gist.github.com/woto/2685cf78168774fd7c841cc8f841fd2a (with :output key)

**Comment by marioizquierdo** [comment]
Let me know if there's anything new here.

**Comment by woto** [comment]
Oh, sorry for didn't reply. Yes seems all works fine. Best wishes!

**Pull request closed without merging**
