### PR TITLE
Support proto3 field presence

### PR DESCRIPTION
**Pull request by sarahegler**
Since protobuf 3.14, the`optional` keyword can be used to distinguish between an unset and default primitive value. However, this code generator does not currently support the `optional` keyword as referenced in the following issue: https://github.com/twitchtv/twirp-ruby/issues/71

This update is to support code generation for protobuf schemas containing the `optional` keyword. It mirrors this change in the corresponding go code generator here: https://github.com/twitchtv/twirp/pull/332

This change required using the [google.golang.org/protobuf](https://pkg.go.dev/mod/google.golang.org/protobuf) module which has superseded the [github.com/golang/protobuf](https://pkg.go.dev/mod/github.com/golang/protobuf) module, hence many changes in `vendor/`. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sarahegler** [comment]
@marioizquierdo can you please take a look at this when you have a chance?

**Comment by wmatveyenko** [comment]
Hi. Thanks for your pull request. Can you document how you tested these changes?

**Comment by sarahegler** [comment]
Hi @wmatveyenko, thanks for taking a look! I tested this in a private repository that uses this code generator using the `protoc` plugin with the `--ruby_out` option. 

When using the latest released version of twirp-ruby without this change, I got the error mentioned in the linked issue `<yourProto>.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-twirp_ruby hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--twirp_ruby_out: `

When using my branch with this change, there was no error and code generation worked as expected. There was only a small change with the move to [google.golang.org/protobuf](https://pkg.go.dev/mod/google.golang.org/protobuf) where `Twirp::Service` is now prefixed with `::`, e.g. instead of `class MyService < ::Twirp::Service` this produced `class MyService < ::Twirp::Service`.

**Comment by wmatveyenko** [comment]
Thanks again for your contribution!

**Pull request merged**
