### PR TITLE
 WIP: Logging Proposal

### PR DESCRIPTION
**Pull request by gwincr11**
Motivation:
  - We added logging into our Twirp app, but it seems like it would be
  ideal to have the framework handle logging instead of adding it to all
  twirp applications. This is a start at what logging could look like, feel free to offer opinions.

To Do:
  - [ ] What should logs look like?
     - [ ] On Success
     - [ ] On Error
  - [ ] What should be included in logs?
     - [ ] On Success
     - [ ] On Error
  - [ ] What log levels should be reported?
     - [ ] On Success
     - [ ] On Error
  - [ ] Where all should logs go in the service class?
  - [ ] Tie in with Rack logging that seems to be already in place and reporting?

Changes:
  - Added a test for sanity.
  - Setup logging in the service for successful transactions and errors.
  - Add an example to test against.

### CODE REVIEW

**Comment by cyrusaf** [comment]
Hi @gwincr11, thanks for opening this PR. Have you taken a look at [service hooks](https://github.com/twitchtv/twirp-ruby/wiki/Service-Hooks) and would they solve this issue for you? Looking at your changes, they seem to be a more specific implementation of the service hooks for logging. In fact, each logging call is invoked directly after a hook in invoked:
- `before` hook https://github.com/twitchtv/twirp-ruby/pull/38/files#diff-bc08c954973b0b0823701e9698e7201fR68 followed `Twirp.logger.info`
- `on_error` hook https://github.com/twitchtv/twirp-ruby/pull/38/files#diff-bc08c954973b0b0823701e9698e7201fR200 followed by `Twirp.logger.error`
- `exception_raised` hook https://github.com/twitchtv/twirp-ruby/pull/38/files#diff-bc08c954973b0b0823701e9698e7201fR219 followed by `Twirp.logger.error`

**Comment by gwincr11** [comment]
@cyrusaf yes, we have implemented logging with service hooks. We were looking to upstream logging since all web apps should have logging in place and it would be ideal not to have to build this for every application we setup on Twirp.

**Comment by gwincr11** [comment]
It was also odd to me that Rack offers some logging out of the box, but the logging stops once it hits the framework. It would be nice to offer complete logging out of the box instead of partial.

**Comment by cyrusaf** [comment]
Thanks for the quick response @gwincr11 . First off, I see the merit in having Twirp logging be similar to Rack logging. To summarize my thoughts below: Given a couple of the following points, I see myself leaning towards using a separate package/gem to provide logging service hooks for your services, so that you only need to write them once. But I would prefer to not build logging directly into the twirp-ruby library itself as I don't want to be opinionated around how consumers should handle logging.

A few thoughts:

1. What advantages does this specific `Twirp.Logger` give over service hooks?

2. When you say:
> it would be ideal not to have to build this for every application we setup on Twirp.

How much effort is it to write service hooks that log? I would imagine it would be a small one time cost for each service. If it is too much effort, then you could write the service hooks once (maybe as a gem) and import them into your services:

```ruby
    def SetupLoggingHooks(svc, logger):
      svc.on_success do |env|
        logger.info({...})
      end
      svc.on_error do |env|
        # ...
      end
      svc.on_exception do |env|
        #...
      end
    end
```

3. Not everyone logs the same. Using service hooks like suggested above is a more component-like architecture that isn’t opinionated about how you log.

To expand on this, a `twerr` can be a 4xx or a 5xx. Not every consumer wants to run `Logger.error` on a 4xx, although some might. Service hooks give consumers the ability to implement logging on their own terms.

I am curious to @marioizquierdo 's thoughts on this as well.

**Comment by gwincr11** [comment]
Thanks @cyrusaf it seems this gem and approach is very inspired by patterns from the Go ecosystem, which is where I assume our philosophical differences are coming from. I would like to address a few reason why I think it is beneficial to move this into the framework and then speak to your Gem idea. Ultimately it is your Gem so I will leave it with this and move on.

1. Consistency: I prefer consistent systems as I find they lower cognitive overhead and developer error.
   - Consistency across Rack and Twirp: Rack is adding logging for the user, but this is not also occurring in Twirp, it is easy to think logging is coming from Twirp and wonder why it doesn't respond with all logs.
   - Consistency across Twirp apps: Since logs are generally used in worst case scenario, it would be nice to ensure baseline logging was always in place and consistent to ensure Developers do not introduce logging bugs that make stressful situations harder to deal with. It would also ensure Developers can look across multiple applications and get consistent logging patterns  by eliminating as much context switching as possible.
   - Better shared tooling: If logs are consistent, it is easier to build consistent graphing and observation tooling around multiple applications.
2. Developer error: It is very easy for a developer to forget to setup a new service with a hook. Given the high priority situation in which logging is used, it is a big mistake to make and may not be noticed until you are in a worst case scenario.
3. Sane defaults: There are a lot of choice to make when setting up logging, some of the choices cannot be made for a developer, but there are places with well defined best practices that many other frameworks already offer. It is nice to not make every developer have to learn and setup these sane defaults, as it is a distraction from core business logic.

I am ok with the Gem idea and have already considered it. There is still no way to ensure all services are registered. We actually built a service registry to handle this on our project to lessen the chance of developer error.

All right, thats my opinion on the matter thanks for listening :)

**Comment by marioizquierdo** [comment]
Hello @gwincr11, thank you for this logging proposal.

Twirp was designed with a unique responsibility in mind: to map HTTP requests into a protobuf service description. Any other functionality is left out on purpose; the hooks are meant to allow plugging any other functionality as needed.

Logging is not simple functionality, unfortunately. Different services have different requirements. Most HTTP frameworks offer default logging solutions, but they are not simple. Full featured frameworks like Rails have complicated code and [extensive docs](https://guides.rubyonrails.org/debugging_rails_applications.html) to deal with logging. Hannami also has extensive [logging support](https://guides.hanamirb.org/projects/logging/), which is not easy to implement and requires managing environments, etc. Simpler frameworks like Sinatra have very [basic logging support](http://sinatrarb.com/intro.html#Logging) but also [problematic configurations](https://github.com/sinatra/sinatra/issues/484). [Ramaze logging](https://github.com/Ramaze/ramaze/blob/master/guide/general/logging.md) is pretty much assigning a logger accessor. Grape offers [basic logging configuration](https://github.com/ruby-grape/grape#logging), anything after that goes into a different gem [grape_logging](https://github.com/aserafin/grape_logging). I'm afraid that if we want to offer a reasonable logging functionality in Twirp-Ruby, it would require a decent amount of planning and work, because it needs to be highly configurable.

That said, I sympathize with the idea of having sane defaults, which also help reduce developer error and increase consistency.

For most cases [Rack::CommonLogger](https://github.com/rack/rack/blob/master/lib/rack/common_logger.rb) should be a simple drop-in solution. For example, in a `config.ru` file (starting the app with the `rackup` command):

```ruby
# log every request in standard Apache format
logger = Logger.new('log/app.log')
use Rack::CommonLogger, logger

run YourTwirpApp.new
```

I also like the idea of adding hooks with logging, a method to `setup_logging_hooks(service, logger)` would be nice. If it doesn't fit a specific service's needs, at least it works as an example on how to setup a logger to log all the requests and errors. I would prefer if that exists in a different gem, but I would be happy to include it as an example in our docs.

Maybe we are not ready to offer a full-featured logging solution, but I'm starting to think we should be able to provide a page in our docs with some reasonable examples. @gwincr11 your experience using Twirp-Ruby will be very useful for that.

**Comment by gwincr11** [comment]
@marioizquierdo thanks for the feedback. I am happy to work up some docs when I have some time to put them together and see what you think. Should I open an issue since it is in the wiki?

Also I am wondering we may deal with the developer error issue? 

One idea I have is adding before and after hooks that run on every request maybe nice. Is this perhaps what was mean by:

> I also like the idea of adding hooks with logging, a method to setup_logging_hooks(service, logger) would be nice.

**Comment by marioizquierdo** [comment]
I'll try to write the first draft in the wiki for logging. Then will post it here in this PR so you can review it and see if it makes sense from your experience, and add anything that you consider relevant.

With the logging hooks, I mean using an example function like the one @cyrusaf suggested, so it is easy to setup a service with logging hooks. Adding the hooks automatically would be nice as a default option, but it would be a non-backwards update, requiring all existing users to explicitly opt out when updating, it would be a major update. So, for now it is easier to suggest or offer an easy drop-in line like this one:

```ruby
def setup_logging_hooks(svc, logger):
  svc.before do |rack_env, env|
    env[:request_start_time] = Time.now
  end

  svc.on_success do |env|
    duration_ms = ((Time.now - env[:request_start_time]) * 1000).to_i
    logger.info("#{svc.service_name}.#{env[:rpc_method]} [#{duration_ms}ms] OK")
  end

  svc.on_error do |twerr, env|
    duration_ms = ((Time.now - env[:request_start_time]) * 1000).to_i
    logger.info("#{svc.service_name}.#{env[:rpc_method]} [#{duration_ms}ms] #{twerr.to_s}")
  end

  svc.exception_raised do |e, env|
    logger.error("[Exception] #{e}\n#{e.backtrace.join("\n")}")
  end
end
```

And then an example of how to setup a service with this function. Then from here, some people will need to log the request parameters, others may need to filter out sensitive data, others may want to send the exceptions to Rollbar/Airbrake/Sentri/Jira/etc. instead of logging, others may want to log in debug level, others may want to configure differently for staging and production, etc. In lack of a configurable logging service, this at least provides a decent placeholder to implement any custom configuration.

**Comment by marioizquierdo** [comment]
@gwincr11 @cyrusaf I wrote a first pass on the wiki about logging: https://github.com/twitchtv/twirp-ruby/wiki/Logging

Let me know if that is clear enough, and if it could be expanded with more examples or ideas. Thanks!

**Comment by gwincr11** [comment]
Thanks this looks great

**Pull request closed without merging**
